workflows:
  simple-workflow:
    name: BookExplorer
    max_build_duration: 60
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Run tests
        script: ./gradlew test
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - overlay128@gmail.com
